blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),
]

bookmark/urls.py
from django.urls import path
from .views import BookmarkListView, BookmarkCreateView, BookmarkDetailView, BookmarkUpdateView, BookmarkDeleteView

app_name = 'bookmark'

urlpatterns = [
    path('', BookmarkListView.as_view(), name='list'),
    path('add/', BookmarkCreateView.as_view(), name='add'),
    path('detail/<int:pk>', BookmarkDetailView.as_view(), name='detail'),
    path('update/<int:pk>', BookmarkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BookmarkDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('polls/', include('polls.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path
from .import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns=[
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results.
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/chart/', views.result_chart, name='chart'),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
        default=timezone.now)
    published_date = models.DateTimeField(
        blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

bookmark/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Bookmark(models.Model):
    site_name = models.CharField(max_length=100)
    url = models.URLField('Site URL')
    def __str__(self):
        #객체를 출력할 때 나타날 값
        return "이름 : "+self.site_name+", 주소 : "+self.url

    def get_absolute_url(self):
        return reverse('bookmark:detail', args=[str(self.id)])

home/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

blog/views.py
from django.utils import timezone
from .models import Post
from django.shortcuts import render, get_object_or_404, redirect
from .forms import PostForm

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        post.delete()
        return redirect('blog:post_list')
    else:
        return render(request, 'blog/post_confirm_delete.html', {'post': post})

bookmark/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from .models import Bookmark
from django.urls import reverse_lazy

# Create your views here.
class BookmarkListView(ListView):
    model = Bookmark
    paginate_by = 6

class BookmarkCreateView(CreateView):
    model = Bookmark
    fields = ['site_name', 'url']
    success_url = reverse_lazy('bookmark:list')
    template_name_suffix = '_create'

class BookmarkDetailView(DetailView):
    model = Bookmark

class BookmarkUpdateView(UpdateView):
    model = Bookmark
    fields = ['site_name', 'url']
    template_name_suffix = '_update'

class BookmarkDeleteView(DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:list')

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class HomeView(TemplateView):
    template_name = 'home/home.html'

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic
import json

### Generic View (class-based views)
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    """Return the last five published questions."""
    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    for id_check in request.POST.getlist('choice'):
        try:
            selected_choice = question.choice_set.get(pk=id_check)
        except(KeyError, Choice.DoesNotExist):
            return render(request, 'polls/detail.html', {'question':question, 'error_message':"You didn't select a choice."})
        else:
            selected_choice.votes += 1
            selected_choice.save()

    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def make_chart_data(data_question):
    my_data = list()
    for choice in data_question.choice_set.all():
        my_dict = dict()
        my_dict['name'] = choice.choice_text
        my_dict['y'] = choice.votes
        my_data.append(my_dict)

    chart_data = [{
        'name': 'Votes',
        'colorByPoint': 'true',
        'data': my_data,
    }]

    return chart_data

def result_chart(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    chart_data = make_chart_data(question)
    dump = json.dumps(chart_data)

    chart_title = {
        'text': '투표결과 <br>' + question.question_text
    }

    dump_title = json.dumps(chart_title)

    return render(request, 'polls/chart.html', {'chart_data':dump, 'chart_title':dump_title})

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>

    {% load static %}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme min css">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Myeongjo&display=swap" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>

</head>
<body>
<div class="container">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home:home' %}">Django Bookmark</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'polls:index' %}">Polls <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'bookmark:list' %}">Bookmark <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'blog:post_list' %}">Blog <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="page-header">
        {% if user.is_authenticated %}
            <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span> </a>
        {% endif %}
        <h1><a href="{% url 'blog:post_list' %}">HYWU Blog</a></h1>
    </div>
    <div class="content container">
      <div class="row">
        <div class="col-md-8">
            {% block content %}
            {% endblock %}
        </div>
      </div>
    </div>

</div>


</body>
</html>

blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
Post Confirm Delete
{% endblock %}

{% block content %}
{% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">

        <div class="page-header">
            {% if user.is_authenticated %}
                <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span> </a>
            {% endif %}
            <h1><a href="{% url 'blog:post_list' %}">Dear My Space</a></h1>
        </div>
        <div class="post-box" style="padding: 50px">
          <form action ="" method="post">
            {% csrf_token %}
            <div class="alert alert-danger">"{{ post.title }}" 포스트를 정말 삭제하시겠습니까?</div>
              <!--              취소-->
              <a href="{% url 'blog:post_detail' pk=post.pk %}" class="btn btn-info">Cancel</a>
              <!--              삭제-->
              <input type="submit" value="Delete" class="btn btn-danger">
          </form>
        </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block title %}
Post detail
{% endblock %}
    {% block content %}
    {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">

        <div class="page-header">
            <!--            로그인 되어있을 경우-->
            {% if user.is_authenticated %}
                <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span> </a>
                <a href="http://127.0.0.1:8000/admin" class="top-menu"
                   style="font-size: medium; line-height: 50px;">
                    로그아웃
                </a>
            <!--            로그인 되어있지 않을 경우-->
            {% else %}
                <a href="http://127.0.0.1:8000/admin" class="top-menu"
                   style="font-size: medium; line-height: 50px;">
                    로그인
                </a>
            {% endif %}
            <h1><a href="{% url 'blog:post_list' %}">Dear My Space</a></h1>
        </div>
        <div class="post-box">
        <div class="post">
            {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
            {% endif %}
            {% if user.is_authenticated %}
                <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span> </a>
                <a class="btn btn-default" href="{% url 'blog:post_delete' pk=post.pk %}"><span class="glyphicon glyphicon-trash"></span> </a>
            {% endif %}
            <a class="btn btn-default" href="{% url 'blog:post_list' %}">목록 </a>
            <h1>{{ post.title }}</h1>
            <p>{{ post.text|linebreaksbr }}</p>
        </div>
        </div>
    {% endblock %}

blog/templates/blog/post_edit.html
{% extends 'base.html' %}
{% block title %}
Post edit
{% endblock %}
{% block content %}
{% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">

        <div class="page-header">
            <!--            로그인 되어있을 경우-->
            {% if user.is_authenticated %}
                <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span> </a>
                <a href="http://127.0.0.1:8000/admin" class="top-menu"
                   style="font-size: medium; line-height: 50px;">
                    로그아웃
                </a>
            <!--            로그인 되어있지 않을 경우-->
            {% else %}
                <a href="http://127.0.0.1:8000/admin" class="top-menu"
                   style="font-size: medium; line-height: 50px;">
                    로그인
                </a>
            {% endif %}
            <h1><a href="{% url 'blog:post_list' %}">Dear My Space</a></h1>
        </div>
        <div class="post-box" style="padding: 50px">
        <h1>New post</h1>
        <form method="POST" class="post-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
            <a href="{% url 'blog:post_list' %}" class="save btn btn-default">Cancel</a>
        </form>
        </div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% block title %}
Post list
{% endblock %}
    {% block content %}
    {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">

        <img src="../../static/blog/images/bg1.jpg" class="bg1"/>
        <img src="../../static/blog/images/bg2.jpg" class="bg2"/>
        <img src="../../static/blog/images/bg9.jpg" class="bg9"/>
        <img src="../../static/blog/images/bg5.jpg" class="bg5"/>
        <img src="../../static/blog/images/bg6.jpg" class="bg6"/>
        <img src="../../static/blog/images/bg6.jpg" class="bg66"/>
        <img src="../../static/blog/images/bg4.jpg" class="bg3"/>
        <div class="page-header">

            <!--            로그인 되어있을 경우-->
            {% if user.is_authenticated %}
                <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span> </a>
                <a href="{% url 'admin:index' %}" class="top-menu"
                   style="font-size: medium; line-height: 50px;">
                    로그아웃
                </a>
            <!--            로그인 되어있지 않을 경우-->
            {% else %}
                <a href="{% url 'admin:index' %}" class="top-menu"
                   style="font-size: medium; line-height: 50px;">
                    로그인
                </a>
            {% endif %}
            <h1><a href="{% url 'blog:post_list' %}">Dear My Space</a></h1>
        </div>
        <div class="post-box">
        {% for post in posts %}
            <div class="post">
                <div class="date">
                    {{ post.published_date }}
                </div>
                <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
                <p>{{ post.text|linebreaksbr }}</p>
            </div>
            <hr/>
        {% endfor %}
        </div>
    {% endblock %}

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
Confirm Delete
{% endblock %}

{% block content %}
  <form action ="" method="post">
    {% csrf_token %}
    <div class="alert alert-danger">Do you want to delete Bookmark "{{object}}"?</div>
    <!--              취소-->
    <a href="{% url 'bookmark:list' %}" class="btn btn-info">Cancel</a>
    <!--              삭제-->
    <input type="submit" value="Delete" class="btn btn-danger">
  </form>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% block title %}
Detail
{% endblock %}

{% block content %}
  {{object.site_name}}<br/>
  {{object.url}}
<br>
<br>
<a href="{% url 'bookmark:list' %}" class="btn btn">back to list</a>
<a href="{% url 'bookmark:update' pk=bookmark.id %}" class="btn btn-success btn-sm">Modify</a>
<a href="{% url 'bookmark:delete' pk=bookmark.id %}" class="btn btn-danger btn-sm">Delete</a>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% block title %}
Bookmark List
{% endblock %}

{% block content %}
    <div class="btn-group">
        <a href="{% url 'bookmark:add' %}" class="btn btn-info">Add Bookmark</a>
    </div>
    <p></p>
    <table class="table">
        <thead>
            <tr>
                <td scope="col">#</td>
                <td scope="col">Site</td>
                <td scope="col">URL</td>
                <td scope="col">Modify</td>
                <td scope="col">Delete</td>
            </tr>
        </thead>
        <tbody>
            {% for bookmark in object_list %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td><a href="{% url 'bookmark:detail' pk=bookmark.id %}">{{bookmark.site_name}}</a></td>
                    <td><a href="{{bookmark.url}}" target="_blank">{{bookmark.url}}</a></td>
                    <td><a href="{% url 'bookmark:update' pk=bookmark.id %}" class="btn btn-success btn-sm">Modify</a></td>
                    <td><a href="{% url 'bookmark:delete' pk=bookmark.id %}" class="btn btn-danger btn-sm">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block pagination %}
    {% if is_paginated %}
    <ul class="pagination justify-content-center pagination-sm">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{% url 'bookmark:list' %}?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Previous</a>
        </li>
        {% endif %}

    {% for object in page_obj.paginator.page_range %}
    <li class="page-item {% if page_obj.number == forloop.counter %}disabled{% endif %}">
        <a class="page-link" href="{{ request.path }}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
    </li>
    {% endfor %}

    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="{% url 'bookmark:list' %}?page={{ page_obj.next_page_number }}">Next</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
        </li>
    {% endif %}
    </ul>
    {% endif %}
{% endblock %}

polls/templates/polls/detail.html
{% extends 'base.html' %}

{% block title %} Polls detail{% endblock %}
{% block content %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{%  static 'polls/style-detail.css' %}">

    <div class="choice">
        <h1 class="title" style="line-height: 35px">{{question.question_text}}</h1>
        {% if error_message %} <p> <strong>{{error_message}}</strong></p>{% endif %}

        <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type ="checkbox" name="choice" id="choice{{forloop.counter}}"  value="{{choice.id}}">
            <label for ="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
        {% endfor %}
        <input type="submit" value="Vote">
        </form>
        <a class="again" href="{% url 'polls:index' %}">Choose Question again?</a>
        <br>
        <a class="again" href="{% url 'polls:results' question.id %}">Show results</a>
    </div>
{% endblock %}

polls/templates/polls/index.html
{% extends 'base.html' %}

{% block title %} Polls list{% endblock %}
{% block content %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{%  static 'polls/style-list.css' %}">

    <div class="container">
        <div class="question">
            <h1 class="title">Polls</h1>
            <br>
            <h4 class="title">Choose question!</h4>
            <br>
            <div class="list">
            {% if latest_question_list %}
                <ul>
                    {% for question in latest_question_list %}
                    <li class="q">
                        <p>{{question.question_text}}</p>
                        <a href="{% url 'polls:detail' question.id %}" class="btn btn-info btn-sm">Vote</a>
                        <a href="{% url 'polls:results' question.id %}" class="btn btn-info btn-sm">Result</a>
                        <a href="{% url 'polls:chart' question.id %}" class="btn btn-info btn-sm">Chart</a>
                    </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No polls are available.</p>
            {% endif %}
            </div>
        </div>

        </iframe>
    </div>
{% endblock %}

polls/templates/polls/results.html
{% extends 'base.html' %}

{% block title %} Polls results{% endblock %}
{% block content %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{%  static 'polls/style-result.css' %}">

    <div class="vote">
        <h1 class="title" style="line-height: 35px">{{question.question_text}}</h1>
        <ul>
            {% for choice in question.choice_set.all %}
            <li class="q">{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
            {% endfor %}
        </ul>

        <a href="{% url 'polls:index' %}">Choose Question again?</a>
        <br>
        <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
        <br>
        <a href="{% url 'polls:chart' question.id %}">Show Chart</a>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"></script>

        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme min css">
        <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext">

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nanum+Myeongjo&display=swap">

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Sunflower:wght@500&display=swap" rel="stylesheet">

    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<div class="container">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
<!--        홈 화면-->
        <a class="navbar-brand" href="{% url 'home:home' %}">Django Project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
<!--                    홈 화면-->
                    <a class="nav-link" href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
<!--                    설문조사 화면-->
                    <a class="nav-link" href="{% url 'polls:index' %}">Polls <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
<!--                    북마크 화면-->
                    <a class="nav-link" href="{% url 'bookmark:list' %}">Bookmark <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
<!--                    블로그 화면-->
                    <a class="nav-link" href="{% url 'blog:post_list' %}">Blog <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>

    <p></p>
    <div class="row">
        <div class="col">
            {% block content %}
            {% endblock %}

            {% block pagination %}
            {% endblock %}
        </div>
    </div>

</div>

</body>
</html>